### ok 
GET http://localhost:3000/auth/
### this is the customer register route
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "Pa11l0100aasaancos@gmail.com",
    "password": "220000"
}

### this is login route
POST http://localhost:3000/auth/login
Content-Type: application/json

{
     "email": "admin121@gmail.com",
    "password": "3333333333"
}
### this is the update user route
PATCH http://localhost:3000/auth/Update
Content-Type: application/json

{
    "email": "Pal100sancos@gmail.com",
    "password": "222222221",
    "new_email": "Pal11000sancos@gmail.com",
    "new_password": "2222222211"
}

### this is the refresh route 

POST http://localhost:3000/auth/refresh
Content-Type: application/json

{
    "refreshToken": "3a9884be69025ef58a4625ec3bb134dc2cbeb891236fd101028b3c6855f4c2ad6372d079c3ff8e6929294f457ed560791ea6ceec1cf8cd9ee633fdae4138bff2"
}

### user sign out
Delete http://localhost:3000/auth/logout
Content-Type: application/json

{ 
     "refreshToken": "744b8fd0814359824238f73e269f7ff6d6a3184f1596ed405b0c533f931748d34c21adfde3e19877c42a943e82295656e2a3259f7086e9566ab343bc435a73cc"
}



### this is for the users to change the state to inactive themselves
DELETE http://localhost:3000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY0NjA0OGE0LTY1YzQtNDhiNS1hNzI1LWNjZTgwZjZmNDY1MSIsImVtYWlsIjoiUGExMWwwMTAwYWFzYWFuY29zQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc4MzU1MDMzOSwiZXhwIjoxNzgzNTUxMjM5fQ.Ju2nTVNO-PYUL5NSCYOD8XYxqqRT0ceIWnnKtOMofy8
