
### ok 
GET http://localhost:3000/

### ok
GET http://localhost:3000/Marta
### ok
POST http://localhost:3000/
Content-Type: application/json

{
    "name": "Martali",
    "birth": "1990-05-15",
    "email": "marta20a1@gmail.com"
}

### ok

Patch http://localhost:3000/b7475b80-68de-4aa6-8286-232ef301648a
Content-Type: application/json

{
    "name": "Martineasaal",
    "birth": "1990-05-15",
    "email": "marta21@gmail.com"
}
### ok
DELETE  http://localhost:3000/
Content-Type: application/json

{
    "id": "8d360a6e-22d3-4694-b73e-c977c89bd5c1"
}