
### ok
GET http://localhost:3000/membership

### ok
GET http://localhost:3000/membership/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM2NDdlYTUzLTczNzMtNDczNS1iZTczLTQ3MDYyOThlNjJmZiIsImVtYWlsIjoiUGFsYW5jb0BnbWFpbC5jb20iLCJyb2xlIjoiY3VzdG9tZXIiLCJpYXQiOjE3ODIyNTU5MTYsImV4cCI6MTc4MjI1NjgxNn0.4965glEOoTzpae9ChmBZamhGFuz5mZvkmVy67z4o-Sw
### ok 
POST http://localhost:3000/membership/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFhZjM2MjZhLTJjNGQtNDI5MS1iZmUzLTgyZDIxNTRlMGEzMyIsImVtYWlsIjoiUGExbDAxMDBhYXNhYW5jb3NAZ21haWwuY29tIiwicm9sZSI6ImN1c3RvbWVyIiwiaWF0IjoxNzgyNDQ3NzE1LCJleHAiOjE3ODI0NDg2MTV9.3cDXnBumrTi23c6Im8CeV3FwlKQkvtrrk6tf-SUJ-Yo
Content-Type: application/json

{
    "type": "vip"
}
### pausar membership
Patch http://localhost:3000/membership/status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM2NDdlYTUzLTczNzMtNDczNS1iZTczLTQ3MDYyOThlNjJmZiIsImVtYWlsIjoiUGFsYW5jb0BnbWFpbC5jb20iLCJyb2xlIjoiY3VzdG9tZXIiLCJpYXQiOjE3ODIyNTU5MTYsImV4cCI6MTc4MjI1NjgxNn0.4965glEOoTzpae9ChmBZamhGFuz5mZvkmVy67z4o-Sw
### ok 

Patch http://localhost:3000/membership/type
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM2NDdlYTUzLTczNzMtNDczNS1iZTczLTQ3MDYyOThlNjJmZiIsImVtYWlsIjoiUGFsYW5jb0BnbWFpbC5jb20iLCJyb2xlIjoiY3VzdG9tZXIiLCJpYXQiOjE3ODIyNTU5MTYsImV4cCI6MTc4MjI1NjgxNn0.4965glEOoTzpae9ChmBZamhGFuz5mZvkmVy67z4o-Sw
### ok 