### ok
GET http://localhost:3000/payments/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFhZjM2MjZhLTJjNGQtNDI5MS1iZmUzLTgyZDIxNTRlMGEzMyIsImVtYWlsIjoiUGExbDAxMDBhYXNhYW5jb3NAZ21haWwuY29tIiwicm9sZSI6ImN1c3RvbWVyIiwiaWF0IjoxNzgyNDQ4Nzk1LCJleHAiOjE3ODI0NDk2OTV9.iqNOv0zEIlVJ_XdicJ6cxAcKVoKNXMFokuSQIyN-MKE

### ok
POST http://localhost:3000/payments/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFhZjM2MjZhLTJjNGQtNDI5MS1iZmUzLTgyZDIxNTRlMGEzMyIsImVtYWlsIjoiUGExbDAxMDBhYXNhYW5jb3NAZ21haWwuY29tIiwicm9sZSI6ImN1c3RvbWVyIiwiaWF0IjoxNzgyNDUwMTkyLCJleHAiOjE3ODI0NTEwOTJ9.qWMiAKwOgOhIr6ahXAyp-7clWueL_YGvZZAiuDvkiTQ

