### ok
GET http://localhost:3000/payments/
Authorization: BearereyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM2NDdlYTUzLTczNzMtNDczNS1iZTczLTQ3MDYyOThlNjJmZiIsImVtYWlsIjoiUGFsYW5jb0BnbWFpbC5jb20iLCJyb2xlIjoiY3VzdG9tZXIiLCJpYXQiOjE3ODIxNTk2OTIsImV4cCI6MTc4MjE2MDU5Mn0.PGLLgUKMOThPcMH-vkxk3yuuHWBb7qnghSu4stkRXls

### ok
POST http://localhost:3000/payments/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM2NDdlYTUzLTczNzMtNDczNS1iZTczLTQ3MDYyOThlNjJmZiIsImVtYWlsIjoiUGFsYW5jb0BnbWFpbC5jb20iLCJyb2xlIjoiY3VzdG9tZXIiLCJpYXQiOjE3ODIyNTY0NTMsImV4cCI6MTc4MjI1NzM1M30.9FHHDHgy7byAsTi5rpNka2vtZfI4XCUBSMcCXBhhqLc
